### ISSUE TITLE
centos5 archived rpms are missing repodata

### ISSUE THREAD

**Issue by al3xxx** [iuscommunity/ius.io#31]
Hello,
 I'm not really sure if this is the right place to mention it. I've noticed just a coupla days ago that ius-archive packages related to centos 5(recently EOL'ed) are missing  repodata/repomd.xml blocking people (myself included) from updating their current live Centos 5 to the latest available IUS packages. Could you please rebuild repodata for http://dl.iuscommunity.org/pub/ius/archive/CentOS/5/x86_64 ?
Thank you.

**Comment by b-harper** [comment]
Hey @al3xxx,

Please see [this thread][0], regarding the status of EL5.

[0]: https://github.com/iuscommunity/announce/issues/4
