### ISSUE TITLE
*.iuscommunity.org ssl cert expired

### ISSUE THREAD

**Issue by babbottscott** [iuscommunity/ius.io#37]
Appears the SSL cert for *.iuscommunity.org has expired
> $ openssl s_client -connect centos6.iuscommunity.org:443 -status
> CONNECTED(00000003)
> OCSP response: no response sent
> depth=3 C = ZA, ST = Western Cape, L = Cape Town, O = Thawte Consulting cc, OU = Certification Services Division, CN = Thawte Premium Server CA, emailAddress = premium-server@thawte.com
> verify return:1
> depth=2 C = US, O = "thawte, Inc.", OU = Certification Services Division, OU = "(c) 2006 thawte, Inc. - For authorized use only", CN = thawte Primary Root CA
> verify return:1
> depth=1 C = US, O = "thawte, Inc.", CN = thawte SSL CA - G2
> verify return:1
> depth=0 C = US, ST = Texas, L = San Antonio, O = "Rackspace US, Inc.", OU = RPM Development, CN = *.iuscommunity.org
> verify error:num=10:certificate has expired
> notAfter=May  8 23:59:59 2018 GMT
> verify return:1
> depth=0 C = US, ST = Texas, L = San Antonio, O = "Rackspace US, Inc.", OU = RPM Development, CN = *.iuscommunity.org
> notAfter=May  8 23:59:59 2018 GMT
> verify return:1
>

**Comment by carlwgeorge** [comment]
Thanks for reaching out.  The correct repo for this type of thing is https://github.com/iuscommunity/infrastructure.  It has been reported (and resolved) in https://github.com/iuscommunity/infrastructure/issues/8.
